const { getGovernanceSummary, getPermissionProfile, isWritableProfile, PERMISSION_PROFILES, renderGovernanceMarkdown } = require('../src/governance');

describe('Governance', () => {
  test('getGovernanceSummary returns required fields', () => {
    const summary = getGovernanceSummary();
    expect(summary.permissionProfiles).toBeTruthy();
    expect(summary.hookRegistry).toBeTruthy();
    expect(summary.policyPacks).toBeTruthy();
    expect(summary.permissionProfiles.length).toBeGreaterThanOrEqual(3);
    expect(summary.hookRegistry.length).toBeGreaterThanOrEqual(1);
  });

  test('read-only profile is not writable', () => {
    expect(isWritableProfile('read-only')).toBe(false);
    expect(isWritableProfile('suggest-only')).toBe(false);
  });

  test('safe-write profile is writable', () => {
    expect(isWritableProfile('safe-write')).toBe(true);
    expect(isWritableProfile('power-user')).toBe(true);
  });

  test('unknown profile falls back to safe-write', () => {
    const profile = getPermissionProfile('nonexistent');
    expect(profile.key).toBe('safe-write');
  });

  test('renderGovernanceMarkdown includes version footer', () => {
    const summary = getGovernanceSummary();
    const md = renderGovernanceMarkdown(summary);
    expect(md).toContain('Generated by claudex-setup');
    expect(md).toContain('Governance Report');
  });
});
