/**
 * Canonical Platform Capability Matrix
 *
 * Single source of truth for platform strengths/weaknesses.
 * Used by: harmony/advisor.js, synergy/routing.js, synergy/compensation.js
 *
 * Scale: 1 (weak) to 5 (best-in-class)
 * All keys use camelCase for consistency.
 */

const PLATFORM_CAPABILITIES = {
  claude: {
    label: 'Claude Code',
    reasoning: 5,
    refactoring: 5,
    debugging: 5,
    review: 5,
    architecture: 5,
    ci: 2,
    ide: 2,
    ui: 1,
    async: 3,
    inline: 3,
    context: 4,
    automation: 4,
    sandbox: 3,
    cloudTasks: 3,
    cloudAgent: 2,
    background: 3,
    governance: 4,
  },
  codex: {
    label: 'Codex',
    reasoning: 4,
    refactoring: 4,
    debugging: 3,
    review: 4,
    architecture: 3,
    ci: 5,
    ide: 3,
    ui: 2,
    async: 5,
    inline: 2,
    context: 3,
    automation: 4,
    sandbox: 4,
    cloudTasks: 5,
    cloudAgent: 4,
    background: 4,
    governance: 3,
  },
  gemini: {
    label: 'Gemini CLI',
    reasoning: 4,
    refactoring: 3,
    debugging: 3,
    review: 3,
    architecture: 3,
    ci: 3,
    ide: 3,
    ui: 2,
    async: 4,
    inline: 2,
    context: 5,
    automation: 3,
    sandbox: 5,
    cloudTasks: 4,
    cloudAgent: 3,
    background: 3,
    governance: 2,
  },
  copilot: {
    label: 'GitHub Copilot',
    reasoning: 3,
    refactoring: 3,
    debugging: 3,
    review: 3,
    architecture: 2,
    ci: 4,
    ide: 4,
    ui: 3,
    async: 3,
    inline: 5,
    context: 3,
    automation: 3,
    sandbox: 2,
    cloudTasks: 4,
    cloudAgent: 4,
    background: 3,
    governance: 3,
  },
  cursor: {
    label: 'Cursor',
    reasoning: 3,
    refactoring: 4,
    debugging: 4,
    review: 3,
    architecture: 3,
    ci: 2,
    ide: 5,
    ui: 5,
    async: 2,
    inline: 4,
    context: 3,
    automation: 4,
    sandbox: 2,
    cloudTasks: 2,
    cloudAgent: 2,
    background: 4,
    governance: 2,
  },
};

const CAPABILITY_LABELS = {
  reasoning: 'Complex reasoning & analysis',
  refactoring: 'Code refactoring',
  debugging: 'Bug diagnosis & debugging',
  review: 'Code review',
  architecture: 'Architecture design',
  ci: 'CI/CD pipeline integration',
  ide: 'IDE integration',
  ui: 'UI/frontend work',
  async: 'Async/background tasks',
  inline: 'Inline code completion',
  context: 'Large context handling',
  automation: 'Workflow automation',
  sandbox: 'Sandboxed execution',
  cloudTasks: 'Cloud-based tasks',
  cloudAgent: 'Cloud agent mode',
  background: 'Background processing',
  governance: 'Governance & permissions',
};

module.exports = { PLATFORM_CAPABILITIES, CAPABILITY_LABELS };
