/**
 * Aider Setup — file generation for .aider.conf.yml, .env, conventions, .gitignore
 *
 * Aider setup families:
 * - .aider.conf.yml (main config)
 * - .env (API keys)
 * - CONVENTIONS.md (project conventions, explicitly passed via read:)
 * - .aiderignore (file exclusion)
 * - .gitignore additions (exclude .aider* artifacts)
 */

const fs = require('fs');
const path = require('path');
const { version } = require('../../package.json');
const { STACKS } = require('../techniques');
const { writeActivityArtifact, writeRollbackArtifact } = require('../activity');
const { AiderProjectContext } = require('./context');
const { recommendAiderMcpPacks } = require('./mcp-packs');

function detectScripts(ctx) {
  const pkg = ctx.jsonFile('package.json');
  if (!pkg || !pkg.scripts) return {};
  return pkg.scripts;
}

function detectProjectName(ctx) {
  const pkg = ctx.jsonFile('package.json');
  if (pkg && pkg.name) return pkg.name;
  return path.basename(ctx.dir);
}

function hasStack(stacks, key) {
  return stacks.some((item) => item.key === key);
}

function buildLintCmd(ctx, stacks) {
  const scripts = detectScripts(ctx);
  if (scripts.lint) return 'npm run lint';
  if (hasStack(stacks, 'python') || hasStack(stacks, 'fastapi') || hasStack(stacks, 'django')) return 'ruff check --fix .';
  if (hasStack(stacks, 'go')) return 'golangci-lint run';
  if (hasStack(stacks, 'rust')) return 'cargo clippy --fix --allow-dirty';
  return null;
}

function buildTestCmd(ctx, stacks) {
  const scripts = detectScripts(ctx);
  if (scripts.test) return 'npm test';
  if (hasStack(stacks, 'python') || hasStack(stacks, 'fastapi') || hasStack(stacks, 'django')) return 'pytest';
  if (hasStack(stacks, 'go')) return 'go test ./...';
  if (hasStack(stacks, 'rust')) return 'cargo test';
  return null;
}

function buildMermaid(stacks) {
  if (hasStack(stacks, 'nextjs')) {
    return [
      '```mermaid',
      'graph TD',
      '    UI[App Router / Pages] --> Logic[Server Actions or API Routes]',
      '    Logic --> Data[Data Layer]',
      '    Data --> External[External Services / DB]',
      '```',
    ].join('\n');
  }

  if (hasStack(stacks, 'fastapi') || hasStack(stacks, 'django') || hasStack(stacks, 'python')) {
    return [
      '```mermaid',
      'graph TD',
      '    API[API / CLI Entry] --> Services[Service Layer]',
      '    Services --> Models[Models / Schemas]',
      '    Models --> Data[Database or External APIs]',
      '```',
    ].join('\n');
  }

  if (hasStack(stacks, 'go')) {
    return [
      '```mermaid',
      'graph TD',
      '    Cmd[cmd/ or main package] --> Internal[internal/ packages]',
      '    Internal --> Data[Storage / APIs]',
      '```',
    ].join('\n');
  }

  return [
    '```mermaid',
    'graph TD',
    '    Entry[Entry Point] --> Core[Core Logic]',
    '    Core --> Data[Data / External Services]',
    '```',
  ].join('\n');
}

/**
 * Build .aider.conf.yml content.
 */
function buildAiderConfYml(ctx, stacks) {
  const name = detectProjectName(ctx);
  const lintCmd = buildLintCmd(ctx, stacks);
  const testCmd = buildTestCmd(ctx, stacks);

  const lines = [
    `# Aider configuration for ${name}`,
    `# Generated by nerviq v${version}`,
    `# Precedence: env vars > CLI args > this file > defaults`,
    '',
    '# --- Model Configuration ---',
    '# model: claude-sonnet-4-20250514',
    '# editor-model: claude-sonnet-4-20250514',
    '# weak-model: gpt-4o-mini',
    '',
    '# --- Architect Mode (2-model workflow) ---',
    '# architect: true',
    '',
    '# --- Git Safety ---',
    'auto-commits: true',
    'dirty-commits: true',
    'attribute-author: true',
    'attribute-committer: true',
    'aider-commit-prefix: "aider: "',
    '',
    '# --- Verification Loop ---',
  ];

  if (lintCmd) {
    lines.push(`lint-cmd: "${lintCmd}"`);
    lines.push('auto-lint: true');
  } else {
    lines.push('# lint-cmd: "your lint command"');
    lines.push('# auto-lint: true');
  }

  if (testCmd) {
    lines.push(`test-cmd: "${testCmd}"`);
    lines.push('auto-test: true');
  } else {
    lines.push('# test-cmd: "your test command"');
    lines.push('# auto-test: true');
  }

  lines.push('');
  lines.push('# --- Context ---');
  lines.push('read:');
  lines.push('  - CONVENTIONS.md');
  lines.push('');
  lines.push('# --- Performance ---');
  lines.push('cache-prompts: true');
  lines.push('# map-tokens: 2048');
  lines.push('');
  lines.push('# --- Display ---');
  lines.push('show-diffs: true');
  lines.push('pretty: true');
  lines.push('# dark-mode: true');
  lines.push('');

  return lines.join('\n');
}

/**
 * Build CONVENTIONS.md content for Aider.
 */
function buildConventionsMd(ctx, stacks) {
  const name = detectProjectName(ctx);
  const mermaid = buildMermaid(stacks);
  const lintCmd = buildLintCmd(ctx, stacks);
  const testCmd = buildTestCmd(ctx, stacks);

  const lines = [
    `# ${name} — Project Conventions`,
    '',
    '## Architecture',
    '',
    mermaid,
    '',
    '## Verification Commands',
    '',
  ];

  if (testCmd) lines.push(`- Test: \`${testCmd}\``);
  if (lintCmd) lines.push(`- Lint: \`${lintCmd}\``);

  const scripts = detectScripts(ctx);
  if (scripts.build) lines.push(`- Build: \`npm run build\``);

  lines.push('');
  lines.push('## Coding Standards');
  lines.push('');
  lines.push('- Follow existing code style and patterns');
  lines.push('- Add tests for new functionality');
  lines.push('- Keep functions small and focused');
  lines.push('- Use descriptive variable and function names');
  lines.push('');
  lines.push('## Error Handling');
  lines.push('');
  lines.push('- Handle errors explicitly, do not swallow exceptions');
  lines.push('- Return meaningful error messages');
  lines.push('');
  lines.push('## Git Workflow');
  lines.push('');
  lines.push('- Aider auto-commits changes (git is the undo mechanism)');
  lines.push('- Use `/undo` to revert the last Aider change');
  lines.push('- Use `/run` to execute shell commands');
  lines.push('- Use `/test` to run tests');
  lines.push('- Use `/add` and `/drop` to manage files in context');
  lines.push('');

  return lines.join('\n');
}

/**
 * Build .env template content.
 */
function buildEnvTemplate() {
  return [
    '# API Keys for Aider',
    '# Uncomment the provider you use:',
    '',
    '# OpenAI',
    '# OPENAI_API_KEY=sk-...',
    '',
    '# Anthropic',
    '# ANTHROPIC_API_KEY=sk-ant-...',
    '',
    '# OpenRouter (multi-provider)',
    '# OPENROUTER_API_KEY=sk-or-...',
    '',
    '# DeepSeek',
    '# DEEPSEEK_API_KEY=sk-...',
    '',
  ].join('\n');
}

/**
 * Build .aiderignore content.
 */
function buildAiderignore(ctx, stacks) {
  const lines = [
    '# Files Aider should not edit',
    '# Uses .gitignore syntax',
    '',
    '# Dependencies',
    'node_modules/',
    '__pycache__/',
    '.venv/',
    'venv/',
    '',
    '# Build artifacts',
    'dist/',
    'build/',
    '.next/',
    '',
    '# Data and large files',
    '*.csv',
    '*.parquet',
    '*.sqlite',
    '*.db',
    '',
    '# Generated files',
    'package-lock.json',
    'yarn.lock',
    'pnpm-lock.yaml',
    'poetry.lock',
    '',
  ];

  return lines.join('\n');
}

/**
 * Build .gitignore additions for Aider artifacts.
 */
function buildGitignoreAdditions() {
  return [
    '',
    '# Aider artifacts',
    '.aider*',
    '.env',
    '',
  ].join('\n');
}

function buildAiderSetupFiles(ctx, stacks) {
  const files = [];

  files.push({
    path: '.aider.conf.yml',
    content: buildAiderConfYml(ctx, stacks),
    label: 'Aider config',
  });

  files.push({
    path: 'CONVENTIONS.md',
    content: buildConventionsMd(ctx, stacks),
    label: 'Convention file',
  });

  files.push({
    path: '.env',
    content: buildEnvTemplate(),
    label: 'Environment template',
  });

  files.push({
    path: '.aiderignore',
    content: buildAiderignore(ctx, stacks),
    label: 'Aider ignore file',
  });

  return files;
}

/**
 * Main setup entry point — detects stacks, writes files, logs activity.
 */
function setupAider(options = {}) {
  const dir = options.dir || process.cwd();
  const log = options.log || console.log;
  const dryRun = options.dryRun || false;

  const ctx = new AiderProjectContext(dir);
  const stacks = ctx.detectStacks(STACKS);

  const setupFiles = buildAiderSetupFiles(ctx, stacks);

  const writtenFiles = [];
  const preservedFiles = [];

  for (const file of setupFiles) {
    const fullPath = path.join(dir, file.path);
    const exists = fs.existsSync(fullPath);

    if (exists && !options.overwrite) {
      preservedFiles.push(file.path);
      continue;
    }

    if (!dryRun) {
      const dirName = path.dirname(fullPath);
      if (!fs.existsSync(dirName)) {
        fs.mkdirSync(dirName, { recursive: true });
      }
      fs.writeFileSync(fullPath, file.content, 'utf8');
    }

    writtenFiles.push(file.path);
  }

  // Handle .gitignore additions (append, don't overwrite)
  const gitignorePath = path.join(dir, '.gitignore');
  if (!dryRun) {
    const existing = fs.existsSync(gitignorePath) ? fs.readFileSync(gitignorePath, 'utf8') : '';
    if (!/\.aider/i.test(existing)) {
      fs.appendFileSync(gitignorePath, buildGitignoreAdditions(), 'utf8');
      writtenFiles.push('.gitignore (appended)');
    }
  }

  // Activity artifacts
  let rollbackArtifact = null;
  let activityArtifact = null;

  if (!dryRun && writtenFiles.length > 0) {
    rollbackArtifact = writeRollbackArtifact(dir, 'aider-setup', writtenFiles);
    activityArtifact = writeActivityArtifact(dir, 'aider-setup', {
      platform: 'aider',
      writtenFiles,
      preservedFiles,
      stacks: stacks.map(s => s.key),
    });
  }

  log('');
  log(`  \x1b[1mAider Setup\x1b[0m — powered by nerviq v${version}`);
  log('');
  log(`  \x1b[32m${writtenFiles.length} files created.\x1b[0m`);
  if (preservedFiles.length > 0) {
    log(`  \x1b[2m${preservedFiles.length} existing files preserved (not overwritten).\x1b[0m`);
  }
  if (rollbackArtifact) {
    log(`  Rollback: \x1b[1m${rollbackArtifact.relativePath}\x1b[0m`);
  }
  log('');
  log('  Run \x1b[1mnpx nerviq --platform aider\x1b[0m to audit your Aider setup.');
  log('');

  return {
    created: writtenFiles.length,
    skipped: preservedFiles.length,
    writtenFiles,
    preservedFiles,
    stacks,
    rollbackArtifact: rollbackArtifact ? rollbackArtifact.relativePath : null,
    activityArtifact: activityArtifact ? activityArtifact.relativePath : null,
  };
}

module.exports = {
  buildAiderConfYml,
  buildConventionsMd,
  buildAiderSetupFiles,
  setupAider,
};
