/**
 * Nerviq Migrate
 *
 * Helps migrate configuration files from one version/format of a platform
 * to a newer version, applying safe in-place transformations.
 *
 * Supports:
 *   cursor  v2 → v3   (legacy .cursorrules → .cursor/rules/*.mdc)
 *   codex   v1 → v2   (AGENTS.md additions, .codex/ bootstrap)
 *   aider   v0 → v1   (basic .aider.conf.yml creation from CLI pattern)
 *   gemini  v1 → v2   (.gemini/ settings.json schema update)
 */

'use strict';

const fs = require('fs');
const path = require('path');

const COLORS = {
  reset: '\x1b[0m',
  bold: '\x1b[1m',
  dim: '\x1b[2m',
  red: '\x1b[31m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  blue: '\x1b[36m',
};

function c(text, color) {
  return `${COLORS[color] || ''}${text}${COLORS.reset}`;
}

// ─── Migration definitions ───────────────────────────────────────────────────

const MIGRATIONS = {
  cursor: {
    'v2→v3': {
      description: 'Migrate legacy .cursorrules to .cursor/rules/*.mdc with proper frontmatter',
      from: 'v2',
      to: 'v3',
      detect: (dir) => {
        const hasLegacy = fs.existsSync(path.join(dir, '.cursorrules'));
        const hasMdc = fs.existsSync(path.join(dir, '.cursor', 'rules'));
        return { applicable: hasLegacy, notes: hasLegacy ? (hasMdc ? 'Legacy .cursorrules present alongside .cursor/rules/ (coexistence)' : 'Legacy .cursorrules present, no .cursor/rules/ yet') : 'No legacy .cursorrules found' };
      },
      apply: (dir, { dryRun = false } = {}) => {
        const legacyPath = path.join(dir, '.cursorrules');
        if (!fs.existsSync(legacyPath)) return { changes: [], warnings: ['No .cursorrules found'] };

        const content = fs.readFileSync(legacyPath, 'utf8').trim();
        const targetDir = path.join(dir, '.cursor', 'rules');
        const targetFile = path.join(targetDir, 'core.mdc');

        const mdcContent = [
          '---',
          'alwaysApply: true',
          '---',
          '',
          content,
          '',
        ].join('\n');

        const changes = [];
        const warnings = [];

        if (fs.existsSync(targetFile)) {
          warnings.push('.cursor/rules/core.mdc already exists — skipped to avoid overwrite');
        } else {
          if (!dryRun) {
            fs.mkdirSync(targetDir, { recursive: true });
            fs.writeFileSync(targetFile, mdcContent, 'utf8');
          }
          changes.push({ action: dryRun ? 'would-create' : 'created', file: '.cursor/rules/core.mdc', detail: 'Converted from .cursorrules with alwaysApply: true' });
        }

        // Optionally rename .cursorrules → .cursorrules.migrated
        const migratedPath = path.join(dir, '.cursorrules.migrated');
        if (!fs.existsSync(migratedPath) && !dryRun) {
          fs.renameSync(legacyPath, migratedPath);
          changes.push({ action: 'renamed', file: '.cursorrules → .cursorrules.migrated', detail: 'Preserved as backup' });
        } else if (dryRun) {
          changes.push({ action: 'would-rename', file: '.cursorrules → .cursorrules.migrated', detail: 'Backup rename' });
        }

        return { changes, warnings };
      },
    },
  },

  codex: {
    'v1→v2': {
      description: 'Bootstrap .codex/ directory with config.toml and update AGENTS.md',
      from: 'v1',
      to: 'v2',
      detect: (dir) => {
        const hasAgents = fs.existsSync(path.join(dir, 'AGENTS.md'));
        const hasCodexDir = fs.existsSync(path.join(dir, '.codex'));
        return {
          applicable: hasAgents && !hasCodexDir,
          notes: !hasAgents
            ? 'No AGENTS.md found'
            : hasCodexDir
              ? '.codex/ already exists'
              : 'AGENTS.md found, .codex/ missing — upgrade applicable',
        };
      },
      apply: (dir, { dryRun = false } = {}) => {
        const changes = [];
        const warnings = [];
        const codexDir = path.join(dir, '.codex');

        if (!fs.existsSync(codexDir)) {
          const configToml = [
            '# Codex configuration — generated by nerviq migrate',
            '[agent]',
            'auto_approve = false',
            '',
            '[context]',
            'files = ["AGENTS.md"]',
            '',
          ].join('\n');

          if (!dryRun) {
            fs.mkdirSync(codexDir, { recursive: true });
            fs.writeFileSync(path.join(codexDir, 'config.toml'), configToml, 'utf8');
          }
          changes.push({ action: dryRun ? 'would-create' : 'created', file: '.codex/config.toml', detail: 'Codex config with safe defaults' });
        } else {
          warnings.push('.codex/ already exists');
        }

        return { changes, warnings };
      },
    },
  },

  aider: {
    'v0→v1': {
      description: 'Create .aider.conf.yml if missing and add .aider* to .gitignore',
      from: 'v0',
      to: 'v1',
      detect: (dir) => {
        const hasConf = fs.existsSync(path.join(dir, '.aider.conf.yml'));
        return {
          applicable: !hasConf,
          notes: hasConf ? '.aider.conf.yml already exists' : 'No .aider.conf.yml found — migration applicable',
        };
      },
      apply: (dir, { dryRun = false } = {}) => {
        const changes = [];
        const warnings = [];

        const confPath = path.join(dir, '.aider.conf.yml');
        if (!fs.existsSync(confPath)) {
          const conf = [
            '# Aider configuration — generated by nerviq migrate',
            'auto-commits: true',
            'auto-lint: false',
            'auto-test: false',
            '# model: gpt-4o',
            '# weak-model: gpt-4o-mini',
            '# edit-format: diff',
          ].join('\n') + '\n';
          if (!dryRun) fs.writeFileSync(confPath, conf, 'utf8');
          changes.push({ action: dryRun ? 'would-create' : 'created', file: '.aider.conf.yml', detail: 'Safe defaults with auto-commits enabled' });
        }

        const gitignorePath = path.join(dir, '.gitignore');
        if (fs.existsSync(gitignorePath)) {
          const gi = fs.readFileSync(gitignorePath, 'utf8');
          if (!/\.aider/i.test(gi)) {
            if (!dryRun) fs.appendFileSync(gitignorePath, '\n# Aider artifacts\n.aider*\n');
            changes.push({ action: dryRun ? 'would-append' : 'appended', file: '.gitignore', detail: 'Added .aider* pattern' });
          } else {
            warnings.push('.gitignore already has .aider* pattern');
          }
        }

        return { changes, warnings };
      },
    },
  },

  gemini: {
    'v1→v2': {
      description: 'Update .gemini/settings.json schema (model field: string → object)',
      from: 'v1',
      to: 'v2',
      detect: (dir) => {
        const settingsPath = path.join(dir, '.gemini', 'settings.json');
        if (!fs.existsSync(settingsPath)) {
          return { applicable: false, notes: 'No .gemini/settings.json found' };
        }
        try {
          const settings = JSON.parse(fs.readFileSync(settingsPath, 'utf8'));
          const needsMigration = typeof settings.model === 'string';
          return {
            applicable: needsMigration,
            notes: needsMigration
              ? `model field is a string "${settings.model}" — needs to be an object`
              : 'model field already uses object format',
          };
        } catch {
          return { applicable: false, notes: 'settings.json is invalid JSON' };
        }
      },
      apply: (dir, { dryRun = false } = {}) => {
        const changes = [];
        const warnings = [];
        const settingsPath = path.join(dir, '.gemini', 'settings.json');

        if (!fs.existsSync(settingsPath)) {
          warnings.push('.gemini/settings.json not found');
          return { changes, warnings };
        }

        let settings;
        try {
          settings = JSON.parse(fs.readFileSync(settingsPath, 'utf8'));
        } catch {
          warnings.push('settings.json is invalid JSON — skipped');
          return { changes, warnings };
        }

        if (typeof settings.model === 'string') {
          const oldModel = settings.model;
          settings.model = { name: oldModel };
          if (!dryRun) fs.writeFileSync(settingsPath, JSON.stringify(settings, null, 2) + '\n', 'utf8');
          changes.push({
            action: dryRun ? 'would-update' : 'updated',
            file: '.gemini/settings.json',
            detail: `model: "${oldModel}" → { name: "${oldModel}" }`,
          });
        } else {
          warnings.push('model field already in correct format');
        }

        return { changes, warnings };
      },
    },
  },
};

// ─── Main migrate function ────────────────────────────────────────────────────

async function runMigrate({ dir = process.cwd(), platform, from: fromVersion, to: toVersion, dryRun = false, json = false } = {}) {
  if (!platform) throw new Error('--platform is required. Example: nerviq migrate --platform cursor --from v2 --to v3');

  const platformMigrations = MIGRATIONS[platform];
  if (!platformMigrations) {
    throw new Error(`No migrations available for platform '${platform}'. Supported: ${Object.keys(MIGRATIONS).join(', ')}.\nUsage: nerviq migrate --platform <platform> [--from <version> --to <version>]`);
  }

  // Determine migration key
  let migrationKey = null;
  if (fromVersion && toVersion) {
    migrationKey = `${fromVersion}→${toVersion}`;
  } else {
    // Auto-detect applicable migration
    for (const [key, migration] of Object.entries(platformMigrations)) {
      const detection = migration.detect(dir);
      if (detection.applicable) {
        migrationKey = key;
        break;
      }
    }
  }

  if (!migrationKey) {
    // Show available migrations
    const availableKeys = Object.keys(platformMigrations);
    const detectionResults = availableKeys.map(key => {
      const detection = platformMigrations[key].detect(dir);
      return { key, ...detection };
    });

    if (json) {
      return JSON.stringify({ platform, status: 'no-migration-applicable', detectionResults }, null, 2);
    }

    const lines = [''];
    lines.push(c(`  nerviq migrate — ${platform}`, 'bold'));
    lines.push('');
    lines.push(c('  No applicable migration found.', 'yellow'));
    lines.push('');
    lines.push('  Available migrations:');
    for (const r of detectionResults) {
      const icon = r.applicable ? c('✓', 'green') : c('-', 'dim');
      lines.push(`    ${icon}  ${r.key.padEnd(10)}  ${r.notes}`);
    }
    lines.push('');
    return lines.join('\n');
  }

  const migration = platformMigrations[migrationKey];
  if (!migration) {
    throw new Error(`Migration '${migrationKey}' not found for platform '${platform}'`);
  }

  const detection = migration.detect(dir);
  const { changes, warnings } = migration.apply(dir, { dryRun });

  const result = {
    platform,
    migration: migrationKey,
    description: migration.description,
    dryRun,
    applicable: detection.applicable,
    detectionNotes: detection.notes,
    changes,
    warnings,
  };

  if (json) return JSON.stringify(result, null, 2);

  const lines = [''];
  lines.push(c(`  nerviq migrate  ${platform} ${migrationKey}`, 'bold'));
  lines.push(c('  ═══════════════════════════════════════', 'dim'));
  lines.push('');
  lines.push(`  ${migration.description}`);
  lines.push(`  Directory: ${dir}`);
  lines.push('');

  if (dryRun) lines.push(c('  Dry run — no files modified', 'yellow'));

  if (changes.length > 0) {
    lines.push('  Changes:');
    for (const ch of changes) {
      const icon = ch.action.startsWith('would') ? c('→', 'blue') : c('✓', 'green');
      lines.push(`    ${icon}  [${ch.action}] ${ch.file}`);
      if (ch.detail) lines.push(c(`         ${ch.detail}`, 'dim'));
    }
  } else {
    lines.push(c('  No changes made.', 'dim'));
  }

  if (warnings.length > 0) {
    lines.push('');
    lines.push('  Warnings:');
    for (const w of warnings) lines.push(`    ${c('⚠', 'yellow')}  ${w}`);
  }

  lines.push('');
  if (!dryRun && changes.length > 0) {
    lines.push(c(`  ✓ Migration complete. Run \`nerviq audit --platform ${platform}\` to verify.`, 'green'));
  } else if (dryRun) {
    lines.push(c('  Run without --dry-run to apply changes.', 'dim'));
  }
  lines.push('');

  return lines.join('\n');
}

module.exports = { runMigrate, MIGRATIONS };
